### ISSUE TITLE
SNN with ideothetic input

### ISSUE THREAD

**Issue by vivekhsridhar** [TomKnowles1994/HeadDirectionPredNet#1]
Hi Tom,

I'm a postdoc at the Max Planck INstitute of Animal Behavior and am working on animal decision-making. As part of my research, I am now trying to construct a ring-attractor model with ideothetic input. Since this should already be part of what you did, I was hoping to use some of NEST code that you've written here. However, I'm new to the NEST framework and am unable to run your code without errors. Currently, this is the error I encounter:

NESTErrors.UnknownComponent: UnknownComponent in SLI function GetDefaults_l: /spike_detector is not a known component.

I was hoping you could help me debug this and get to a working implementation of such a ring-attractor.

Thank You.

Vivek

**Comment by TomKnowles1994** [comment]
Hi Vivek,

Thank you for your interest in our project, I'll do my best to get your code working.

As a first check, which version of NEST are you using? This code has only been tested with NEST 2.18

**Comment by TomKnowles1994** [comment]
I've also added an environment.yml to the NEST folder, so you can replicate the setup we used

**Comment by vivekhsridhar** [comment]
Thanks a lot for your quick response! I'll try using this and get back to you if I have more questions.

Cheers!
Vivek

**Comment by vivekhsridhar** [comment]
Dear Tom,

I have now gotten past that error and modified the few lines to make this work with NEST 3.3. The other issue now seems to be related to directing the file paths to the right directories. In cell [8] of the HD_SNN_corrections.ipynb, we read in a data file at posedata = pd.read_csv(...)

Here, I get the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/circling_distal.csv'

To get past this, I downloaded data from your WeTransfer link, and pasted the directory to the following file there
'whiskeye_head_direction_circling_distal/raw_pose.csv'. Is this correct? Could you perhaps tell me briefly what this data file contains?

Thanks again for your help!! I really appreciate it. I can also send a pull request to update the code to work with NEST 3.3 if you like (but no pressure if you'd rather keep the current version as it went with the paper)?

Cheers!
Vivek

**Comment by TomKnowles1994** [comment]
Hi Vivek,

You should be able to use any of the datasets provided (rotating, circling, random_x). The file you want is called pose.csv. You _can_ use raw_pose.csv if you want more datapoints, but the image files match up to the pose.csv file, whereas raw_pose.csv is the pose data recorded prior to this filtering.

If you only care about using odometry as input, then either is fine, but if you want to pass the images to a machine learning system and input the allothetically-derived estimates of head direction, then you'll need to stick with pose.csv

pose.csv contains 5 fields; index, timestamp, x, y and theta. You'll only need field 4 (the 5th field) if you are sticking to predicting head direction. raw_pose.csv contains 4 fields; timestamp, x, y and theta

As long as you have a theta estimate from somewhere, you can use any dataset you like, be this from a live animal with head stage or a robot, although you'll likely have to re-tune the weights if you do this, as the ring attractor only integrates well within a particular band of velocities.

I appreciate the offer of the upgrade, but we need to keep this code in NEST 2.18 as it ensures compatibility with the NeuroRobotics Platform (I'll add a link to the relevant paper in the README as well). If this wasn't required, we would have used NEST 3.x to write this to begin with.

Hope this helps!

Tom

**Comment by vivekhsridhar** [comment]
Dear Tom,

Thanks so much for this information. I think I have enough to proceed further now. I appreciate your quick response.

Cheers!
Vivek
